### ISSUE TITLE
Shift + Tab doesn't work as expected

### ISSUE THREAD

**Issue by trebmuh** [brummer10/GxReverseDelay.lv2#6]
Shift + Tab is meant to make the _previous_ controller active if one is to believe the README.md file but it actually make the _next_ controller active.

**Comment by brummer10** [comment]
Ah, yes it suffer from the same issue then this
https://github.com/brummer10/GxFenderizer.lv2/issues/2

Thanks for reporting, should be fixed now.
regards
hermann

**Comment by trebmuh** [comment]
Thanks for the quick fix.
Working as expected now.
:+1:
